### ISSUE TITLE
Minor bug. When clearing subreddit value from search bar , it doesnt show back 'gifs' (default) gifs. 

### ISSUE THREAD

**Issue by kalpakprajapati15** [joshuamorony/angularstart-giflist#1]
When clearing the search bar, it should show default gifs again. It isn't doing this as subreddit is null in  `https://www.reddit.com/r/${subreddit}/hot/.json?limit=100`. 

Solution: We can add map operator to subredditChanged$ - if subreddit is null, then return 'gifs';  else return as it is; 

P.S : Really inspired by the reactive nature of your code. 🥇

**Comment by joshuamorony** [comment]
Good catch! I've just pushed a fix for this
