### ISSUE TITLE
How would you resolve pagination 

### ISSUE THREAD

**Issue by cskiwi** [joshuamorony/angularstart-giflist#2]
Hi,

I really like the pattern, but in your example you have a pagination based on the lastGif,
but changing it to a normal pagination, would you still do the same? or move it to the state? 

I worked the following out, but  when I change the filter, I wanted to reset the page number, and this felt wrong on how to do this.

```ts
 //sources
  pagination$ = new BehaviorSubject<number>(1);
  private error$ = new Subject<string | null>();
  private filterChanged$ = this.filter.valueChanges.pipe(
    tap(() => this.pagination$.next(1)),
    debounceTime(300),
    distinctUntilChanged(),
  );

  private gamesLoaded$ = this.filterChanged$.pipe(
    switchMap((filter) =>
      this.pagination$.pipe(
        distinctUntilChanged(),
        mergeMap((page) => this._loadRecentGamesForPlayer(filter, page)),
      ),
    ),
  );
```

Do you have any suggestions / examples for this?

**Comment by joshuamorony** [comment]
With this particular pattern I'm using signals for the state, so I wouldn't introduce a BehaviorSubject as a state storing mechanism here - instead, I would just have the current page store in the state signal, then when you want to go to the next page you just have your pagination emit the current page in state + 1 e.g. service.pagination$.next(service.currentPage() + 1)

As for reseting the page when the filter changes, a side effect is appropriate for this but I would handle it in the reducer step in the constructor, so have a subscribe set up for "filterChanged$" and when that emits, update the state signal to set the currentPage back to 1.
